# .github/workflows/release.yaml

on:
  push:
    branch: dev

jobs:
  releases-matrix:
    name: Release Go Binary
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - uses: wangyoucao577/go-release-action@v1.37
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: "teldrive"
          extra_files: LICENSE README.md
          goversion: "https://dl.google.com/go/go1.21.1.linux-amd64.tar.gz"
          pre_command: |
              curl -fsSL https://fnm.vercel.app/install | bash
              make sync-ui
              make ui
          release_tag: dev